train:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
#    TODO 修改数据库
    database: train
    username: root
    password: 123456
  wechat:
    appid: wxfc52049f6b81c4a5
    secret: d082ba6582d179679d70d0d143019ef5
  redis:
    port: 6379
    host: localhost
    database: 2